spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wzdemo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 9780619
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # mapper映射文件路径
  configuration:
    # 打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
